[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100

[deploy.healthcheck]
interval = "10s"
timeout = "5s"
retries = 3
startPeriod = "30s"

[deploy.domain]
name = "loving-adaptation.up.railway.app" 